# -*- coding: utf-8 -*-
"""imageprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wpQhifmeer3SRKFkfzdT0zL7ePTcvZwW
"""

#getting an image from web
!wget 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Astronaut-EVA_edit.jpg'

"""libraries that we can use for image processing: matplotlib.image / pillow/ OpenCV(cv2)"""

#importing the image module from matplotlib.image library
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

#loading an image through matplotlib.image module
img = mpimg.imread('/content/Astronaut.jpg')

type(img)

#we have 3 color channel RGB and not a gray image
print(img.shape)

print(img)

#displaying image from a numpy array image
img_plot = plt.imshow(img)
plt.show()

"""resizing the image using pillow libary"""

from PIL import Image

img = Image.open('/content/Astronaut.jpg')
img_resized = img.resize((200,200))

img_resized.save('Astronaut_resized.jpg')

#loading an image through matplotlib.image module
img_resized = mpimg.imread('/content/Astronaut_resized.jpg')

#displaying image from a numpy array image
img_resizedplot = plt.imshow(img_resized)
plt.show()

"""converting RGB image to Gray images using OpenCV"""

import cv2

img = cv2.imread('/content/Astronaut.jpg')

type(img)

img.shape

grayscale_image = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

type(grayscale_image)

grayscale_image.shape

"""cv2.imshow() will display the image but this will not be allowed in google collab"""

from google.colab.patches import cv2_imshow

#displaying the image in gray
cv2_imshow(grayscale_image)

#saving the gray image
cv2.imwrite('Astronaut_gray.jpg', grayscale_image)