# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jHioe8sjwyfAUQhFOvTemHaLvyCacoSi
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt #Fixed typo in module name
import seaborn as sns
import sklearn.datasets
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn import metrics

"""importing the boston house price dataset"""

import numpy as np
import pandas as pd

# Load the Boston housing prices dataset from the original source
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

# Create a Pandas DataFrame
boston_df = pd.DataFrame(data)
boston_df['target'] = target


# # Load the California housing dataset
# from sklearn.datasets import fetch_california_housing
# housing = fetch_california_housing()

# # Load the Ames housing dataset
# from sklearn.datasets import fetch_openml
# housing = fetch_openml(name="house_prices", as_frame=True)

print(boston_df)

import numpy as np
import pandas as pd
#from sklearn.datasets import load_boston # Import the load_boston function Removed deprecated function

# Load the Boston housing dataset from the original source
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

# Create a Pandas DataFrame
boston_df = pd.DataFrame(data)
boston_df['target'] = target

house_price_dataframe = boston_df # Assign boston_df to house_price_dataframe

house_price_dataframe.head()

house_price_dataframe['price'] = house_price_dataframe.target # Changed house_price_dataset to house_price_dataframe

house_price_dataframe.head()

# checking the number of rows and columns
house_price_dataframe.shape

#hecking for missing values
house_price_dataframe.isnull().sum()

#statistical measures of dataset
house_price_dataframe.describe()

"""correlation"""

correlation = house_price_dataframe.corr()

#constructin ga heatmap to understand correlation
plt.figure(figsize=(10,10))
sns.heatmap(correlation,cbar=True,square=True,fmt='.1f',annot=True,annot_kws={'size':8},cmap='Blues')

"""splitting data and target"""

X = house_price_dataframe.drop(['price'],axis=1)
Y = house_price_dataframe['price']

print(X)
print(Y)

"""splitting data into training and test data"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 2)

print(X.shape, X_train.shape, X_test.shape)

"""model training XGBOOST REGRESSOR"""

#LOADING MODEL
model = XGBRegressor()

model.fit(X_train, Y_train)

#evaluation accuracy for prediction on training data
training_data_prediction = model.predict(X_train)

print(training_data_prediction)

#r squad  error
score_1 = metrics.r2_score(Y_train, training_data_prediction)
#mean absolute error
score_2 = metrics.mean_absolute_error(Y_train, training_data_prediction)

print("R squared error : ", score_1)
print('Mean Absolute Error : ', score_2)

"""visualization"""

plt.scatter(Y_train, training_data_prediction)
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual Price vs Predicted Price")
plt.show

"""prediction on test data

"""

test_data_prediction = model.predict(X_test)

score_1 = metrics.r2_score(Y_test, test_data_prediction)
#mean absolute error
score_2 = metrics.mean_absolute_error(Y_test, test_data_prediction)

print("R squared error : ", score_1)
print("mean absolute error: ", score_2)