server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;  # Path where the Vue.js build files are stored (this should be your /dist folder).
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;  # For Vue Router History mode
  }
}
