server.port: 8085
spring:
  data.mongodb.uri: mongodb://localhost:27017/accountingdb
  security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8089/realms/cardence
management.endpoints.web.exposure.include: "*"
