#spring.application.name=MIRAI
## Server Port
#server.port=8080
#
## Database Configuration for PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5433/mirai_main
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
#
## Spring Mail Configuration
##spring.mail.host=smtp.gmail.com
##spring.mail.port=587
##spring.mail.username=your_email@gmail.com
##spring.mail.password=your_email_password
##spring.mail.properties.mail.smtp.auth=true
##spring.mail.properties.mail.smtp.starttls.enable=true
##spring.mail.properties.mail.smtp.starttls.required=true
#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=elghazisilia@gmail.com
#spring.mail.password=nfon svts xhjg llts
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


