[options]
; Mot de passe maître (Master Password) pour gérer les bases
admin_passwd = admin123

; Chemins
data_dir = /var/lib/odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

; Connexion DB (le conteneur Postgres s'appelle "db" dans docker-compose)
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

; Qualité de vie
proxy_mode = False
log_level = info

; (Optionnel) limiter les DB visibles
; dbfilter = ^odoo_events_db$
